attractions:
  - name: melnitsa
    display_name: Мельница
    source_url: https://dreamisland.ru/attractions/melnitsa
    zone: Под куполом
    type: Экстремальные
    height_rule: от 140 см
    express_available: true
    standard_ticket_from_rub: 2700
    express_ticket_from_rub: 7000
  - name: molot_sudby
    display_name: Молот судьбы
    source_url: https://dreamisland.ru/attractions/molot-sudby
    zone: Черепашки-ниндзя
    type: Экстремальные
    height_rule: от 130 см до 185 см
    express_available: true
    standard_ticket_from_rub: 2700
    express_ticket_from_rub: 7000
  - name: immersivnyy_polyet
    display_name: Иммерсивный полёт
    source_url: https://dreamisland.ru/attractions/immersivnyy-polyet
    zone: Замок Снежной королевы
    type: Семейные
    height_rule: 110-130 см в сопровождении, от 130 см без сопровождения
    express_available: true
    standard_ticket_from_rub: 2700
    express_ticket_from_rub: 7000
  - name: laguna
    display_name: Лагуна
    source_url: https://dreamisland.ru/attractions/laguna
    zone: Маугли в стране динозавров
    type: Семейные
    height_rule: 100-120 см в сопровождении, от 120 см без сопровождения
    express_available: true
    standard_ticket_from_rub: 2800
    express_ticket_from_rub: 7400
  - name: lava
    display_name: Лава
    source_url: https://dreamisland.ru/attractions/lava
    zone: Маугли в стране динозавров
    type: Семейные
    height_rule: 120-130 см в сопровождении, от 130 см без сопровождения
    express_available: true
    standard_ticket_from_rub: 2700
    express_ticket_from_rub: 7000
  - name: liany
    display_name: Лианы
    source_url: https://dreamisland.ru/attractions/liany
    zone: Маугли в стране динозавров
    type: Детские
    height_rule: 105-120 см в сопровождении, от 120 см без сопровождения
    express_available: true
    standard_ticket_from_rub: 2800
    express_ticket_from_rub: 7400
  - name: beshenyy_tanets
    display_name: Бешеный танец
    source_url: https://dreamisland.ru/attractions/beshenyy-tanets
    zone: Под куполом
    type: Экстремальные
    height_rule: от 130 см до 190 см
    express_available: true
    standard_ticket_from_rub: 2700
    express_ticket_from_rub: 7000
  - name: na_krylyakh_vetra
    display_name: На крыльях ветра
    source_url: https://dreamisland.ru/attractions/na-krylyakh-vetra
    zone: Маугли в стране динозавров
    type: Семейные
    height_rule: от 120 см до 195 см
    express_available: true
    standard_ticket_from_rub: 2800
    express_ticket_from_rub: 7400
